env:
  node: true
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
  sourceType: module
rules:
  no-console: off
  no-unused-vars: off
  no-constant-condition: off
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
